/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Overview',
      items: [{type: 'autogenerated', dirName: 'overview'}],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [{type: 'autogenerated', dirName: 'core-concepts'}],
    },
    {
      type: 'category',
      label: 'Argus Vault',
      items: [{type: 'autogenerated', dirName: 'argus-vault'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      items: [{type: 'autogenerated', dirName: 'ecosystem'}],
    },
  ],
};

export default sidebars;
